#!/bin/sh

# ---------------------------------------------------------------------
# Example arg parser to experiment with.
# ---------------------------------------------------------------------

help()
{
   echo "This utility will find the differences and by default will concatenate"
   echo "the compared-dataset to the src-dataset."
   echo "The default behavior can be reversed so that src-dataset is appended to"
   echo "compared-dataset by using option '-r'"
   echo "If a third data set is provided, option '-o' is ignored and the two"
   echo "datasets will be merged without any duplicates"
   echo
   echo "Syntax: dconcat [-o|h] <src-dataset> <compared-dataset> <new-dataset>"
   echo "options:"
   echo "r     'true' to reverse the contamination order."
   echo "h     Print this Help."
   echo
}

reverse=''

OPTSTRING="rh:"

while getopts "${OPTSTRING}" opt; do
  case "${opt}" in
    r)
      reverse="true"
      ;;
    h)
      help
      exit 1
      ;;
    ?)
      echo "Error: Invalid option has been declared -${OPTARG}." >&2
      exit 1
      ;;
  esac
done

# Shift processed options to access remaining options
shift "$((OPTIND-1))"

if [ -n "$1" ]; then
    if [[ "$*" =~ "-" ]]; then
        echo "Options must become before values."
        help
        exit 1
    else
        echo "Remaining argument(s): $*"
        echo "1 is $1"
        echo "2 is $2"
        echo "3 is $3"


        # Case: Write ddiff out to a new data set.
        if [ -n "$3" ]; then
            echo "Case: Write ddiff out to a new data set."
            ddiff "$1" "$2" | tail -n +7|grep "^I -" |cut -c5-85 | decho $3
            ddiff "$1" "$2" | tail -n +7|grep "^D -" |cut -c5-85 | decho -a $1
            exit
        fi

        # Case: Write DS1 into DS2 (reverse the write order)
        if [[ "$reverse" == "true" ]]; then
            echo "Case: Write DS1 diff into DS2 (reverse the write order)"
            ddiff "$1" "$2" | tail -n +7|grep "^D -" |cut -c5-85 | decho -a $1
            exit
        fi

        echo "Case: Write DS2 diff into DS1 (reverse the write order)"
        ddiff "$1" "$2" | tail -n +7|grep "^I -" |cut -c5-85 | decho -a $1
        exit
    fi
fi

# set -x
# # Access remaining non-option arguments
# if [ -n "$1" ]; then
#   echo "Remaining argument(s): $*"
# fi

    # if [ "$#" -eq 0 ]; then
    #     echo "No arguments were passed."
    #     # Handle the case of no arguments.
    #     exit 0
    # fi


#     my_flag="true"

# if [[ "$my_flag" == "true" ]]; then
#   echo "The flag is true."
# fi

# # Alternatively, if you treat non-empty string as true:
# if [[ -n "$my_flag" ]]; then
#   echo "The flag is not empty (considered true)."
# fi